namespace $rootnamespace$.Events
{
    using System;

    using EventStore;
    using EventStore.Dispatcher;

    using StealFocus.EventStoreExtensions;
	
    /// <remarks>
    /// Generated by the "StealFocus.EventStoreExtensions" NuGet package.
    /// 
    /// An implementation of <see cref="IEventStoreFactory" />.
    /// </remarks>
    public class EventStoreFactory : IEventStoreFactory
    {
        [CLSCompliant(false)]
        public IStoreEvents Create(string connectionStringKey, IDispatchCommits dispatchCommits)
        {
            return Wireup.Init()
               .LogToOutputWindow()
               .UsingSqlPersistence(connectionStringKey)
                   .InitializeStorageEngine()
                   .UsingJsonSerialization()
                   .UsingSynchronousDispatchScheduler()
                   .DispatchTo(dispatchCommits)
               .Build();
        }
    }
}
